#!/bin/bash

#yum -y -q install dialog

height=30
width=40
choice_height=20
backtitle="Newb Admin"
title="Newb Admin - CentOS"

options=(1 "CentOS Wizard"
         2 "Zabbix Install"
		 3 "Main Index"
         4 "Exit")

choice=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "" \
                $height $width $choice_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

clear
case $choice in
        1) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/centos/nwb-wizard-c
        source ./nwb-wizard-c
        source ./index-c
        ;;
        2) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/centos/monitoring/nwb-zabbix-c
        source ./nwb-zabbix-c
        source ./index-c
        ;;
		3) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/index
		bash ./index
		;;
        4) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/centos/base/cleanup-c
		source ./cleanup-c
		exit
		;;
esac