#!/bin/bash

#yum -y -q install dialog

height=30
width=40
choice_height=20
backtitle="Welcome to Newb Admin"
title="Newb Admin - Main Menu"

options=(1 "CentOS Tools"
         2 "Email Tools"
         3 "Exit")

choice=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "" \
                $height $width $choice_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

clear
case $choice in
        1) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/centos/index-c
        source ./index-c
        source ./index
        ;;
        2) echo "Soon"
		source ./index
        ;;
        3) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/cleanup
		source ./cleanup
		exit
		;;
esac
