#!/bin/bash

# Dependencies
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/centos/base/nwb-deps-c
source ./nwb-deps-c

# SSHD
h1 'Set custom SSHD Port? [Y/n] ' ; read -r sshdport
case ${sshdport,,} in
        [yY][eE][sS]|[yY]|"")
		h2 'New SSHD Port: ' ; read -r sshport
		h3 $'Installing FirewallD ...\n'
		yum -y install firewalld
		systemctl start firewalld
		h3 $'Done - Installing FirewallD\n\n'
			
		h3 $'Setting FirewallD Ports\n'
		firewall-cmd --zone=public --permanent --add-port=$sshport/tcp
		firewall-cmd --zone=public --permanent --add-port=80/tcp
		firewall-cmd --zone=public --permanent --add-port=443/tcp
		if [[ "$os" -eq 7 ]]; then
			echo "This is C7"
		fi
		
		if [[ "$os" -eq 8 ]]; then
			firewall-cmd --zone=public --permanent --remove-service=cockpit
			firewall-cmd --zone=public --permanent --remove-service=dhcpv6-client
		fi
		firewall-cmd --zone=public --permanent --remove-service=ssh
		firewall-cmd --reload
		
		printf '\n'
                h2 'Current FirewallD Rules: '
                printf "$red$bold$(firewall-cmd --list-all | sed -n 's/  ports: *//p')$normal\n\n"
		
		h3 $'Done - Setting FirewallD Ports\n\n'

		h3 $'Adding SELinux SSHD Port Rule\n'
		if [[ "$os" -eq 7 ]]; then
			yum -y install policycoreutils-python
		fi
		
		if [[ "$os" -eq 8 ]]; then
			dnf -y install policycoreutils-python-utils
		fi
		semanage port -a -t ssh_port_t -p tcp $sshport
		h3 $'Done - SELinux SSHD Port Rule\n\n'

		h3 'Changing SSHD Port ... '
		sed -i 's/^#Port 22$/Port ${sshport}/g' /etc/ssh/sshd_config
		cy $'done!\n\n'

		h3 'Restarting SSHD ... '
		systemctl restart sshd
		cy $'done!\n\n'
                ;;
        *) h2 $'Skipping custom SSHD\n\n';
esac
