#!/bin/bash

# Variables & Colors

usage() { echo "Usage: $0 [-i <image_name.img>] [-m <memory>] [-b <bridge>] [-s <storage>] [-v <vm_id>]" 1>&2; exit 1; }

while getopts ":i:m:b:s:v:" o; do
  case "${o}" in
    i)
      i=${OPTARG}
      ;;
    m)
      m=${OPTARG}
      ;;
    b)
      b=${OPTARG}
      ;;
    s)
      s=${OPTARG}
      ;;
    v)
      v=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${i}" ] || [ -z "${m}" ] || [ -z "${b}" ] || [ -z "${s}" ] || [ -z "${v}" ]; then
  usage
fi

img=$i
memory=$m
bridge=$b
storage=$s
vmid=$v
green="\e[1;32m"
reset="\e[0m"

# Script

echo ""
echo -e "${green}[!]${reset} Creating VM with ID: ${green}$vmid${reset}, RAM: ${green}$memory${reset}, Bridge: ${green}$bridge${reset}, Storage: ${green}$storage${reset} ..."
qm create $vmid --memory $memory --net0 virtio,bridge=$bridge

echo ""
echo -e "${green}[!]${reset} Importing disk ..."
qm importdisk $vmid $img $storage

echo ""
echo -e "${green}[!]${reset} Attaching disk ..."
qm set $vmid --scsihw virtio-scsi-pci --scsi0 $storage:vm-$vmid-disk-0

echo ""
echo -e "${green}[!]${reset} Creating Cloud-init drive ..."
qm set $vmid --ide2 $storage:cloudinit

echo ""
echo -e "${green}[!]${reset} Setting Cloud-init drive as bootable ..."
qm set $vmid --boot c --bootdisk scsi0

echo ""
echo -e "${green}[!]${reset} Attaching serial console ..."
qm set $vmid --serial0 socket --vga serial0

echo ""
echo -e "${green}[!]${reset} Generating template ..."
qm template $vmid

echo ""
echo -e "${green}[!]${reset} Finished!"
echo ""
