#!/bin/bash

# Variables & Colors

usage() { echo "Usage: $0 [-h <remote_hostname>] [-s <local_storage>] [-r <remote_workdir_full_path>] [-l <local_workdir_full_path>] [-v <vm_id>]" 1>&2; exit 1; }

while getopts ":h:s:r:l:i:" o; do
  case "${o}" in
    h)
      h=${OPTARG}
      ;;
    s)
      s=${OPTARG}
      ;;
    r)
      r=${OPTARG}
      ;;
    l)
      l=${OPTARG}
      ;;
    v)
      v=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${h}" ] || [ -z "${s}" ] || [ -z "${r}" ] || [ -z "${l}" ] || [ -z "${i}" ]; then
  usage
fi

host=$h
storage=$s
rstorage=$r
lstorage=$l
vm=$v
green="\e[1;32m"
reset="\e[0m"
date=$(date +'%y-%m-%d_%H-%M-%S')
vmfile="vzdump-qemu-$vm-$date.vma.zst"

# Script

ssh -t root@$host "mkdir $rstorage" >/dev/null 2>/dev/null &&
mkdir $lstorage >/dev/null 2>/dev/null &&

echo ""
echo -e "========== ${green} $(date +'%H:%M:%S') | $(date +'%d.%m.%Y') ${reset} =========="

echo ""
echo -e "${green}[!]${reset} Migrating VM ${green}$vm${reset} from host ${green}$host${reset}."

echo ""
echo -e "${green}[!]${reset} Shutting down ... "
ssh -t root@$host "qm shutdown $vm" >/dev/null 2>/dev/null &&

echo ""
echo -e "${green}[!]${reset} Backing up ... "
echo ""
ssh -t root@$host "vzdump $vm --dumpdir $rstorage --mode stop --compress zstd --stdout > $rstorage/$vmfile" &&

echo ""
echo -e "${green}[!]${reset} Copying ... "
echo ""
rsync -av --partial --inplace --append --progress root@"$host":"$rstorage"/"$vmfile" "$lstorage"/"$vmfile" &&

echo ""
echo -e "${green}[!]${reset} Restoring ... "
echo ""
qmrestore $lstorage/$vmfile $vm --storage $storage &&

echo ""
echo -e "${green}[!]${reset} Starting ... "
qm start "$vm" >/dev/null 2>/dev/null &&

echo ""
echo -e "${green}[!]${reset} Disabling old OnBoot ... "
ssh -t root@$host "qm set $vm --onboot 0" >/dev/null 2>/dev/null &&

echo ""
echo -e "${green}[!]${reset} Cleanup ... "
rm -rf $lstorage/*.vma.zst >/dev/null 2>/dev/null &&
ssh -t root@$host "rm -rf $rstorage/*.vma.zst" >/dev/null 2>/dev/null &&
ssh -t root@$host "rm -rf $rstorage/*.log" >>/dev/null 2>/dev/null &&

echo ""
echo -e "Migration ${green}finished${reset} for ${green}VM $vm ${reset}"
echo ""
echo -e "========== ${green} $(date +'%H:%M:%S') | $(date +'%d.%m.%Y') ${reset} =========="
echo ""
