#!/bin/bash

# Variables & Colors
host=$1
storage=$2
rstorage=$3
lstorage=$4
vm=$5
green="\e[1;32m"
reset="\e[0m"
date=$(date +'%y-%m-%d_%H-%M-%S')
vmfile="vzdump-qemu-$vm-$date.vma.zst"

# Script
echo ""
echo -e "========== ${green} $(date +'%H:%M:%S') | $(date +'%d.%m.%Y') ${reset} =========="

echo ""
echo -e "${green}[!]${reset} Migrating VM ${green}$vm${reset} from host ${green}$host${reset}."

echo ""
echo -e "${green}[!]${reset} Shutting down ... "
ssh -t root@$host "qm shutdown $vm" >/dev/null 2>/dev/null &&

echo ""
echo -e "${green}[!]${reset} Backing up ... "
echo ""
ssh -t root@$host "vzdump $vm --dumpdir $rstorage --mode stop --compress zstd --stdout > $rstorage/$vmfile" &&

echo ""
echo -e "${green}[!]${reset} Copying ... "
echo ""
rsync -av --partial --inplace --append --progress root@"$host":"$rstorage"/"$vmfile" "$lstorage"/"$vmfile" &&

echo ""
echo -e "${green}[!]${reset} Restoring ... "
echo ""
qmrestore $lstorage/$vmfile $vm --storage $storage &&

echo ""
echo -e "${green}[!]${reset} Starting ... "
qm start "$vm" >/dev/null 2>/dev/null &&

echo ""
echo -e "${green}[!]${reset} Disabling old OnBoot ... "
ssh -t root@$host "qm set $vm --onboot 0" >/dev/null 2>/dev/null &&

echo ""
echo -e "${green}[!]${reset} Cleanup ... "
rm -rf $lstorage/*.vma.zst >/dev/null 2>/dev/null &&
ssh -t root@$host "rm -rf $rstorage/*.vma.zst" >/dev/null 2>/dev/null &&
ssh -t root@$host "rm -rf $rstorage/*.log" >>/dev/null 2>/dev/null &&

echo ""
echo -e "Migration ${green}finished${reset} for ${green}VM $vm ${reset}"
echo ""
echo -e "========== ${green} $(date +'%H:%M:%S') | $(date +'%d.%m.%Y') ${reset} =========="
echo ""
