#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Install Zabbix
h1 'Install Zabbix? This will remove all existing Zabbix configs! [Y/n] ' ; read -r utils
case ${utils,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Zabbix\n'
					h3 $'Zabbix Version (https://www.zabbix.com/download): ' ; read -r zversion
						apt-get -qq -y purge zabbix-agent && apt-get -qq -y autoclean
						wget https://repo.zabbix.com/zabbix/$zversion/debian/pool/main/z/zabbix-release/zabbix-release_$zversion-1+debian10_all.deb
						dpkg -i zabbix-release_$zversion-1+debian10_all.deb
						rm -rf zabbix-release_$zversion-1+debian10_all.deb
						apt-get -qq -y update && apt-get -qq -y install zabbix-agent
                h2 $'Done - Installing Zabbix\n\n'

				h2 'Apply Zabbix CNCTED Settings? [Y/n] ' ; read -r zcncted
					case ${zcncted,,} in
						[yY][eE][sS]|[yY]|"")
							h2 $'Applying Zabbix CNCTED Settings\n'
								sed -i 's/^Server=127.0.0.1$/Server=zabbix.cncted.net/g' /etc/zabbix/zabbix_agentd.conf &&
								sed -i "s/^Hostname=Zabbix server$/Hostname=$HOSTNAME/g" /etc/zabbix/zabbix_agentd.conf &&
								sed -i "s/^ServerActive=127.0.0.1/#ServerActive=127.0.0.1/g" /etc/zabbix/zabbix_agentd.conf &&
								systemctl restart zabbix-agent
								
								printf "\n${yellow}Public IP:${green} "
								ip -o addr show | \
								grep -v 'inet6' | \
								grep -v 'scope host' | \
								awk '{print $4}' | \
								cut -d '/' -f 1 | \
								grep -vE '^(192\.168|10\.|172\.1[6789]\.|172\.2[0-9]\.|172\.3[01]\.)'
								printf "${normal}\n"
								printf "${yellow}Server Hostname:${green} "
								hostname
								printf "${normal}\n"
								
							h2 $'Done - Applying Zabbix CNCTED Settings\n'
							;;
							*) h2 $'Skipping - Applying Zabbix CNCTED Settings\n'
					esac
				;;
        *) h1 $'Skipping - Install Zabbix\n\n'
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-apps
fi