#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Install Zabbix
h1 'Install Zabbix? [Y/n] ' ; read -r utils
case ${utils,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Zabbix\n'
					h3 $'Zabbix Version: ' ; read -r zversion
						wget https://repo.zabbix.com/zabbix/$zversion/debian/pool/main/z/zabbix-release/zabbix-release_$zversion-1+debian10_all.deb
						dpkg -i zabbix-release_$zversion-1+debian10_all.deb
						rm -rf zabbix-release_$zversion-1+debian10_all.deb
						apt-get -qq -y update && apt-get -qq -y zabbix-agent
                h2 $'Done - Installing Zabbix\n\n'
                ;;
        *) h2 $'Skipping - Install Zabbix\n\n'
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-apps
fi