#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Set Hostname
h1 'Set Hostname? [Y/n] ' ; read -r sethostname
case ${sethostname,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Setting Hostname\n'
			h3 'New hostname: ' ; read -r hostname
				hostnamectl set-hostname "$hostname" --static
                h2 $'Done - Setting Hostname\n\n'
                ;;
        *) h2 $'Skipping - Set Hostname\n\n';
esac

# Footer
footer=nwb-footer
if [ ! -f "$footer" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-footer
fi
source ./nwb-footer