#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Install Docker Compose
h1 'Install Docker Compose? [Y/n] ' ; read -r dockercompose
case ${dockercompose,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Docker Compose\n'
			curl -L https://github.com/docker/compose/releases/latest/download/docker-compose-Linux-x86_64 -o /usr/local/bin/docker-compose
			chmod +x /usr/local/bin/docker-compose
                h2 $'Done - Installing Docker Compose\n\n'
                ;;
        *) h1 $'Skipping - Install Docker Compose\n\n';
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-apps
fi