#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Install Modern PHP
h1 'Install Modern PHP? [Y/n] ' ; read -r php
case ${php,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Modern PHP\n'
			apt-get -qq -y install lsb-release apt-transport-https ca-certificates
			wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
			echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" | sudo tee /etc/apt/sources.list.d/php.list
			apt-get -qq -y update && apt-get -qq -y dist-upgrade && apt-get -qq -y autoremove
			h3 $'PHP Version: ' ; read -r phpversion
				apt-get -qq -y install php"$phpversion"-fpm && apt-get -qq -y install php"$phpversion"-cli php"$phpversion"-curl php"$phpversion"-dom php"$phpversion"-mbstring php"$phpversion"-mcrypt php"$phpversion"-mysqlnd php"$phpversion"-imagick php"$phpversion"-xml php"$phpversion"-gd php"$phpversion"-mcrypt php"$phpversion"-zip php"$phpversion"-imap php"$phpversion"-soap php"$phpversion"-bcmath php"$phpversion"-bz2 php"$phpversion"-tidy php"$phpversion"-xmlrpc php"$phpversion"-intl php"$phpversion"-ldap php"$phpversion"-smbclient php"$phpversion"-gmp php"$phpversion"-json
				systemctl enable php"$phpversion"-fpm
				systemctl start php"$phpversion"-fpm
				dpkg-query -l | grep php"$phpversion"
		h2 $'Done - Installing Modern PHP\n\n'
                ;;
        *) h1 $'Skipping - Install Modern PHP\n\n';
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-apps
fi
