#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Secure SSH
h1 'Secure SSH? [Y/n] ' ; read -r securessh
case ${securessh,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Securing SSH\n'
                        cp /etc/ssh/sshd_config /etc/ssh/sshd_config-bak
                        h3 'New SSH port: ' ; read -r sshport
                                sed -i "s|#Port 22|Port $sshport|g" /etc/ssh/sshd_config
                        h3 'Permit Root Login? [EXPLICIT: yes / no /prohibit-password] ' ; read -r sshroot
                                sed -i "s|#PermitRootLogin prohibit-password|PermitRootLogin $sshroot|g" /etc/ssh/sshd_config
                        h3 'Allow Password Authentication? [EXPLICIT: yes / no] ' ; read -r sshpass
                                sed -i "s|#PasswordAuthentication yes|PasswordAuthentication $sshpass|g" /etc/ssh/sshd_config
                        sed -i 's|#LoginGraceTime 2m|LoginGraceTime 1m|g' /etc/ssh/sshd_config
                        sed -i 's|#StrictModes yes|StrictModes yes|g' /etc/ssh/sshd_config
                        sed -i 's|#MaxAuthTries 6|MaxAuthTries 3|g' /etc/ssh/sshd_config
                        sed -i 's|#MaxSessions 10|MaxSessions 5|g' /etc/ssh/sshd_config
                        sed -i 's|#PermitEmptyPasswords no|PermitEmptyPasswords no|g' /etc/ssh/sshd_config
                        sed -i 's|#UseDNS no|UseDNS no|g' /etc/ssh/sshd_config
                        systemctl restart sshd
                        h3 $'\n= A backup of your initial sshd_config was made to /etc/ssh/sshd_config-bak\n\n'
                h2 $'Done - Securing SSH\n\n'
                ;;
        *) h2 $'Skipping - Secure SSH\n\n';
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-security
fi
