#!/bin/bash
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
source ./nwb-header

h1 'Install fstrim cron? [Y/n] ' ; read -r fstrimcron
case ${fstrimcron,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing fstrim cron\n'
			crontab -l > fstrim
			echo "*/30 * * * * fstrim --all >/dev/null 2>&1" >> fstrim
			crontab fstrim
			rm -rf fstrim
                h2 $'Done - Installing fstrim cron\n\n'
                ;;
        *) h2 $'Skipping - Install fstrim cron\n\n'
esac