#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Apply useradd bash fix
h1 'Apply useradd bash fix? [Y/n] ' ; read -r useraddfix
case ${useraddfix,,} in
        [yY][eE][sS]|[yY]|"")
		h2 $'Applying ueradd bash fix\n'
			sed -i 's|SHELL=/bin/sh|SHELL=/bin/bash|g' /etc/default/useradd
		h2 $'Done - Applying ueradd bash fix\n\n'
                ;;
        *) h2 $'Skipping - Apply useradd bash fix\n\n';
esac

# Footer
footer=nwb-footer
if [ ! -f "$footer" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-footer
fi
source ./nwb-footer