#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
fi
source ./nwb-header

# Install Docker
h1 'Install Docker? [Y/n] ' ; read -r docker
case ${docker,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Docker\n'
			curl -fsSL https://get.docker.com -o get-docker.sh && sh get-docker.sh
			systemctl start docker
			systemctl enable docker
			rm -rf get-docker.sh
                h2 $'Done - Installing Docker\n\n'
                ;;
        *) h2 $'Skipping - Install Docker\n\n';
esac

# Footer
footer=nwb-footer
if [ ! -f "$footer" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-footer
fi
source ./nwb-footer