#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/deps/nwb-header
fi
source ./nwb-header

# Update and Upgrade OS
h1 'Update and Upgrade OS? [Y/n] ' ; read -r osupdate
case ${osupdate,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Updating and Upgrading the OS\n'
                	apt-get -qq -y update && apt-get -qq -y dist-upgrade && apt-get -qq -y autoremove && apt-get -qq -y install sudo
                h2 $'Done - Updating and Upgrading the OS\n\n'
                ;;
        *) h1 $'Skipping - Updating and Upgrading the OS\n\n';
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-ostweaks
fi