#!/bin/bash

# Colors
green="\e[1;32m"
reset="\e[0m"

# Variables
usage() { echo""; echo -e "${green}[!]${reset} Usage: ${green}-i${reset} -d domain.tld"; echo "" 1>&2; exit 1; }

while getopts ":d:" o; do
  case "${o}" in
    d)
      d=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${d}" ]; then
  usage
fi

domain=$d

# Script
echo ""
echo -e "${green}[!]${reset} Setting Google MX for $domain ..."
plesk bin dns --del "$domain" -mx mail -mailexchanger mail."$domain"
plesk bin dns --add "$domain" -mx -mailexchanger aspmx.l.google.com -priority 1
echo ""
