#!/bin/bash

# Colors
green="\e[1;32m"
reset="\e[0m"

# Variables
usage() { echo""; echo -e "${green}[!]${reset} Usage: ${green}-d${reset} domain.tld"; echo "" 1>&2; exit 1; }

while getopts ":d:" o; do
  case "${o}" in
    d)
      d=${OPTARG}
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

if [ -z "${d}" ]; then
  usage
fi

domain=$d

# Script
echo ""
echo -e "${green}[!]${reset} Setting Google MX for $domain ..."
plesk bin dns --del "$domain" -mx '' -mailexchanger mail."$domain"
plesk bin dns --add "$domain" -mx '' -mailexchanger mx.zoho.eu -priority 10
plesk bin dns --add "$domain" -mx '' -mailexchanger mx2.zoho.eu -priority 20
plesk bin dns --add "$domain" -mx '' -mailexchanger mx3.zoho.eu -priority 50
echo ""
