#!/bin/bash

# Style
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)"
normal="$(tput sgr0)"

h1() { printf '%s=== %s%s' "$green" "$1" "$normal"; }
h2() { printf '%s== %s%s' "$yellow" "$1" "$normal"; }
h3() { printf '%s= %s%s' "$cyan" "$1" "$normal"; }
ye() { printf '%s' "$yellow" "$1" "$normal"; }
cy() { printf '%s' "$cyan" "$1" "$normal"; }

# Apply useradd bash fix
h1 'Apply useradd bash fix? [Y/n] ' ; read -r useraddfix
case ${useraddfix,,} in
        [yY][eE][sS]|[yY]|"")
		h2 $'Applying ueradd bash fix\n'
			sed -i 's|SHELL=/bin/sh|SHELL=/bin/bash|g' /etc/default/useradd
		h2 $'Done - Applying ueradd bash fix\n\n'
                ;;
        *) h1 $'Skipping - Apply useradd bash fix\n\n';
esac