#!/bin/bash

# Style
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)"
normal="$(tput sgr0)"

h1() { printf '%s=== %s%s' "$green" "$1" "$normal"; }
h2() { printf '%s== %s%s' "$yellow" "$1" "$normal"; }
h3() { printf '%s= %s%s' "$cyan" "$1" "$normal"; }
ye() { printf '%s' "$yellow" "$1" "$normal"; }
cy() { printf '%s' "$cyan" "$1" "$normal"; }

# Install Certbot
h1 'Install Certbot? [Y/n] ' ; read -r certbot
case ${certbot,,} in
	[yY][eE][sS]|[yY]|"")
		h2 $'Installing Certbot\n'
			apt -qq -y update && apt -qq -y dist-upgrade && apt -qq -y autoremove &&
			apt -qq -y remove certbot &&
			apt -qq -y install snapd &&
			snap install core &&
			sudo sysctl kernel.unprivileged_userns_clone=1 &&
			snap install core; sudo snap refresh core &&
			snap install --classic certbot &&
			ln -s /snap/bin/certbot /usr/bin/certbot **
			h3 $'\n= Issue with "certbot certonly" or "certbot certonly --webroot"\n\n'
		h2 $'Done - Installing Certbot\n\n'
                ;;
*) h1 $'Skipping - Install Certbot\n\n';
esac