#!/bin/bash

# Style
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)"
normal="$(tput sgr0)"

h1() { printf '%s=== %s%s' "$green" "$1" "$normal"; }
h2() { printf '%s== %s%s' "$yellow" "$1" "$normal"; }
h3() { printf '%s= %s%s' "$cyan" "$1" "$normal"; }
ye() { printf '%s' "$yellow" "$1" "$normal"; }
cy() { printf '%s' "$cyan" "$1" "$normal"; }

# Disable IPv6
h1 'Disable IPv6? [Y/n] ' ; read -r disipv6
case ${disipv6,,} in
	[yY][eE][sS]|[yY]|"")
		h2 $'Disabling IPv6\n'
			echo "net.ipv6.conf.all.disable_ipv6 = 1" >> /etc/sysctl.conf
			sysctl -p
                h2 $'Done - Disabling IPv6\n\n'
                ;;
*) h1 $'Skipping - Disable IPv6\n\n'
esac