#!/bin/bash

# Style
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)"
normal="$(tput sgr0)"

h1() { printf '%s=== %s%s' "$green" "$1" "$normal"; }
h2() { printf '%s== %s%s' "$yellow" "$1" "$normal"; }
h3() { printf '%s= %s%s' "$cyan" "$1" "$normal"; }
ye() { printf '%s' "$yellow" "$1" "$normal"; }
cy() { printf '%s' "$cyan" "$1" "$normal"; }

# Install fstrim cron
h1 'Install fstrim cron? [Y/n] ' ; read -r fstrimcron
case ${fstrimcron,,} in
	[yY][eE][sS]|[yY]|"")
		h2 $'Installing fstrim cron\n'
			apt-get -qq -y install cron
			crontab -l > fstrim
			echo "*/30 * * * * fstrim --all >/dev/null 2>&1" >> fstrim-cron
			crontab fstrim-cron
			rm -rf fstrim-cron
		h2 $'Done - Installing fstrim cron\n\n'
                ;;
	*) h1 $'Skipping - Install fstrim cron\n\n'
esac