#!/bin/bash

# Style
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)"
normal="$(tput sgr0)"

h1() { printf '%s=== %s%s' "$green" "$1" "$normal"; }
h2() { printf '%s== %s%s' "$yellow" "$1" "$normal"; }
h3() { printf '%s= %s%s' "$cyan" "$1" "$normal"; }
ye() { printf '%s' "$yellow" "$1" "$normal"; }
cy() { printf '%s' "$cyan" "$1" "$normal"; }

# Install Self-Signed Certificate
h1 'Install Self-Signed Certificate? [Y/n] ' ; read -r selfssl
case ${selfssl,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Self-Signed Certificate\n'
			mkdir /etc/ssl/private
			chmod 700 /etc/ssl/private
			openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
			h3 $'\n= Public Key: /etc/ssl/certs/nginx-selfsigned.crt\n'
			h3 $'Private Key: /etc/ssl/private/nginx-selfsigned.key\n'
		h2 $'Done - Installing Self-Signed Certificate\n\n'
                ;;
        *) h1 $'Skipping - Install Self-Signed Certificate\n\n';
esac