#!/bin/bash

# Style
green="$(tput setaf 2)"
yellow="$(tput setaf 3)"
cyan="$(tput setaf 6)"
normal="$(tput sgr0)"

h1() { printf '%s=== %s%s' "$green" "$1" "$normal"; }
h2() { printf '%s== %s%s' "$yellow" "$1" "$normal"; }
h3() { printf '%s= %s%s' "$cyan" "$1" "$normal"; }
ye() { printf '%s' "$yellow" "$1" "$normal"; }
cy() { printf '%s' "$cyan" "$1" "$normal"; }

# Install Utilities
h1 'Install Utilities? [Y/n] ' ; read -r utils
case ${utils,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Utilities\n'
                	apt-get -qq -y install nano wget sudo curl screen tar unzip qemu-guest-agent acpid rsync software-properties-common
                h2 $'Done - Installing Utilities\n\n'
                ;;
        *) h1 $'Skipping - Install Utilities\n\n'
esac