#!/bin/bash

apt-get -qq -y install dialog

height=30
width=40
choice_height=20
backtitle="Newb Admin - Debian 10"
title="Main Menu"

options=(1 "Installation Wizard"
         2 "OS Tweaks"
         3 "Security"
         4 "Networking"
         5 "Applications"
         99 "Exit")

choice=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "" \
                $height $width $choice_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

clear
case $choice in
        1) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/wizards/wizard-newbadmin
		bash ./wizard-newbadmin
        ;;
        2) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/menus/nwb-ostweaks
		source ./nwb-tweaks
        ;;
        3) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/menus/nwb-security
		source ./nwb-security
		;;
		4) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/menus/nwb-networking
		source ./nwb-networking
		;;
		5) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/menus/nwb-apps
		source ./nwb-apps
		;;
        99) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-cleanup
		bash ./nwb-cleanup
		exit
	;;
esac