#!/bin/bash

apt-get -qq -y install dialog

height=30
width=40
choice_height=20
backtitle="Welcome to Newb Admin for Debian 10"
title="Newb Admin - Main Menu"

options=(1 "Installation Wizard"
         2 "Update OS"
         3 "Exit")

choice=$(dialog --clear \
                --backtitle "$backtitle" \
                --title "$title" \
                --menu "" \
                $height $width $choice_height \
                "${options[@]}" \
                2>&1 >/dev/tty)

clear
case $choice in
        1) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/wizards/nwb-wizard
		bash ./nwb-wizard
        ;;
        2) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-update
		source ./nwb-update
        ;;
        3) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-cleanup
		bash ./nwb-cleanup
		exit
	;;
esac