#!/bin/bash

curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/deps/nwb-header
source ./nwb-header

h1 'Update and Upgrade OS? [Y/n] ' ; read -r update
case ${update,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Updating and Upgrading the OS\n'
                	apt-get -qq -y update && apt-get -qq -y dist-upgrade && apt-get -qq -y autoremove && apt-get -qq -y install sudo
                h2 $'Done - Updating and Upgrading the OS\n\n'
                ;;
        *) h2 $'Skipping - Updating and Upgrading the OS\n\n';
esac