#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian11/deps/nwb-header
fi
source ./nwb-header

# Install Utilities
h1 'Install Utilities? [Y/n] ' ; read -r utils
case ${utils,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Utilities\n'
                	apt-get -qq -y install nano wget sudo curl screen tar unzip qemu-guest-agent acpid rsync software-properties-common &&
                h2 $'Done - Installing Utilities\n\n'
                ;;
        *) h1 $'Skipping - Install Utilities\n\n'
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-ostweaks
fi