#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian11/deps/nwb-header
fi
source ./nwb-header

# Set Time
h1 'Set Time? [Y/n] ' ; read -r settime
case ${settime,,} in
        [yY][eE][sS]|[yY]|"")
		h2 $'Setting Time\n'
			h3 $'Timezone: ' ; read -r timezone
				timedatectl set-timezone "$timezone"
			apt-get -qq -y install chrony
			systemctl enable chrony
			systemctl start chrony
		h2 $'Done - Setting Time\n\n'
                ;;
        *) h1 $'Skipping - Set Time\n\n';
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-ostweaks
fi