#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian11/deps/nwb-header
fi
source ./nwb-header

# Install MariaDB
h1 'Install MariaDB? [Y/n] ' ; read -r mariadb
case ${mariadb,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing MariaDB 10.6\n'
                	apt-get install software-properties-common dirmngr apt-transport-https
					apt-key adv --fetch-keys 'https://mariadb.org/mariadb_release_signing_key.asc'
					add-apt-repository 'deb [arch=amd64,i386,arm64,ppc64el] https://mirror.23m.com/mariadb/repo/10.6/debian bullseye main'
					apt-get -qq -y update && apt-get -qq -y dist-upgrade && apt-get -qq -y autoremove && apt-get -qq -y install mariadb-server
					systemctl enable mariadb && systemctl start mariadb
					mysql_secure_installation
					dpkg-query -l | grep mariadb
                h2 $'Done - Installing MariaDB 10.6 \n\n'
                ;;
        *) h1 $'Skipping - Install MariaDB\n\n';
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-apps
fi