#!/bin/bash

# Header
header=nwb-header
if [ ! -f "$header" ]; then
    curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian11/deps/nwb-header
fi
source ./nwb-header

# Install Self-Signed Certificate
h1 'Install Self-Signed Certificate? [Y/n] ' ; read -r selfssl
case ${selfssl,,} in
        [yY][eE][sS]|[yY]|"")
                h2 $'Installing Self-Signed Certificate\n'
			mkdir /etc/ssl/private
			chmod 700 /etc/ssl/private
			openssl req -x509 -nodes -days 365 -newkey rsa:2048 -keyout /etc/ssl/private/nginx-selfsigned.key -out /etc/ssl/certs/nginx-selfsigned.crt
			h3 $'\n= Public Key: /etc/ssl/certs/nginx-selfsigned.crt\n'
			h3 $'Private Key: /etc/ssl/private/nginx-selfsigned.key\n'
			h3 $'Issue certificates with: certbot certonly --webroot\n'
		h2 $'Done - Installing Self-Signed Certificate\n\n'
                ;;
        *) h1 $'Skipping - Install Self-Signed Certificate\n\n';
esac

# Check if run by Wizard
wizard=wizard-newbadmin
if [ ! -f "$wizard" ]; then
    bash ./nwb-security
fi
