#!/bin/bash
clear

# Apply OS Updates
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-update
source ./nwb-update

# Disable IPv6
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-disableipv6
source ./nwb-disableipv6

# Add fstrim cron
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-fstrim
source ./nwb-fstrim

# Secure SSH
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-ssh
source ./nwb-ssh

# Set Hostname
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-hostname
source ./nwb-hostname

# Set Time
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-time
source ./nwb-time

# Useradd Bash Fix
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-useraddfix
source ./nwb-useraddfix

# Install Utilities
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-utils
source ./nwb-utils

# Enable Auto Updates
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-autoupdate
source ./nwb-autoupdate

# Install Modern PHP
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-php
source ./nwb-php

# Install NGINX
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-nginx
source ./nwb-nginx

# Create Self-Signed Certificate
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-selfssl
source ./nwb-selfssl

# Install Certbot
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-certbot
source ./nwb-certbot

# Install MariaDB
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-mariadb
source ./nwb-mariadb

# InstallDocker
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-docker
source ./nwb-docker

# Install Docker Compose
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-dockercompose
source ./nwb-dockercompose

# Install Git
curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian/tools/nwb-git
source ./nwb-git

# Back to index
index=newbadmin-debian10
if [ -f "$index" ]; then
    bash newbadmin-debian10
else
    exit
fi