#!/bin/bash
height=30
width=40
choice_height=20
backtitle="Newb Admin - Debian 10"
title="Security"

options=(1 "Secure SSH"
	2 "Create Self-Signed Certificate"
	98 "Back to Main Menu"
	99 "Exit")

choice=$(dialog --clear \
	--backtitle "$backtitle" \
	--title "$title" \
	--menu "" \
	$height $width $choice_height \
	"${options[@]}" \
	2>&1 >/dev/tty)

clear
case $choice in
        1) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-ssh
		bash ./nwb-ssh
        ;;
        2) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-selfssl
		bash ./nwb-selfssl
        ;;
	98) bash newbadmin-debian10
	;;
        99) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/deps/nwb-cleanup
		bash ./nwb-cleanup
	exit
	;;
esac
