#!/bin/bash
height=30
width=40
choice_height=20
backtitle="Newb Admin - Debian 10"
title="Applications"

options=(1 "Install NGINX"
	2 "Install Certbot"
	3 "Install Modern PHP"
	4 "Install PHP Composer"
	5 "Install MariaDB"
	6 "Install Docker"
	7 "Install Docker Compose"
	8 "Install Git"
	9 "Install NodeJS"
	10 "Install Zabbix"
	98 "Back to Main Menu"
	99 "Exit")

choice=$(dialog --clear \
	--backtitle "$backtitle" \
	--title "$title" \
	--menu "" \
	$height $width $choice_height \
	"${options[@]}" \
	2>&1 >/dev/tty)

clear
case $choice in
        1) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-nginx
		bash ./nwb-nginx
        ;;
        2) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-certbot
		bash ./nwb-certbot
        ;;
        3) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-php
		bash ./nwb-php
        ;;
	4) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-phpcomposer
		bash ./nwb-phpcomposer
        ;;
        5) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-mariadb
		bash ./nwb-mariadb
        ;;
        6) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-docker
		bash ./nwb-docker
        ;;
        7) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-dockercompose
		bash ./nwb-dockercompose
        ;;
	8) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-git
		bash ./nwb-git
	;;
	9) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-nodejs
		bash ./nwb-nodejs
        ;;
	10) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/tools/nwb-zabbix
		bash ./nwb-zabbix
        ;;
	98) bash newbadmin-debian10
	;;
	99) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/deps/nwb-cleanup
		bash ./nwb-cleanup
	exit
	;;
esac
