#!/bin/bash

filename="${BASH_SOURCE[0]}"
mv -f $filename newbadmin-debian10 2>/dev/null

apt-get -qq -y install dialog

height=30
width=40
choice_height=20
backtitle="Newb Admin - Debian 10"
title="Main Menu"

options=(1 "Installation Wizard"
         2 "OS Tweaks"
         3 "Security"
         4 "Networking"
         5 "Applications"
         99 "Exit")

choice=$(dialog --clear \
	--backtitle "$backtitle" \
	--title "$title" \
	--menu "" \
	$height $width $choice_height \
	"${options[@]}" \
	2>&1 >/dev/tty)

clear
case $choice in
        1) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/wizards/wizard-newbadmin
		source ./wizard-newbadmin
        ;;
        2) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/menus/nwb-ostweaks
		source ./nwb-ostweaks
        ;;
        3) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/menus/nwb-security
		source ./nwb-security
	;;
	4) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/menus/nwb-networking
		source ./nwb-networking
	;;
	5) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/menus/nwb-apps
		source ./nwb-apps
	;;
        99) curl -Os https://raw.githubusercontent.com/Razva/newbadmin/master/debian10/deps/nwb-cleanup
		source ./nwb-cleanup
	exit
	;;
esac
